# Generated by Django 4.2.1 on 2023-08-07 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_dispatch_detail_party_details_sales_invoice_sales_voucher_stock_item_allocation_sales_voucher_stock_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_category',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.companies'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='per',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='units',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
